# NUMPY PRACTISE

In [ ]:
import numpy as np

relation = np.array(["Dost","Best","Friend"])
relation

In [7]:
future=np.array([5,10,15])
future

array([ 5, 10, 15])

In [9]:
type(relation)

numpy.ndarray

In [10]:
type(future)

numpy.ndarray

In [12]:
len(future)

3

In [13]:
len(relation)

3

In [14]:
relation[1]

'Best'

In [15]:
future.mean()

10.0

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
np.empty(4)

array([7.86844187e-312, 7.86844187e-312, 7.86844421e-312, 3.75489891e-322])

In [21]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
# table of 6
np.arange(6,66,6)

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54, 60])

In [30]:
# lin space
np.linspace(2,20, num=10)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [37]:
np.ones(10, dtype=np.float16)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float16)

# ARRAY PRACTISE

In [39]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [41]:
x.sort()
x

array([1, 2, 3, 4, 5])

In [42]:
y = np.array([6,7,8,9,10])
y

array([ 6,  7,  8,  9, 10])

In [45]:
z = np.concatenate((y,x))
z

array([ 6,  7,  8,  9, 10,  1,  2,  3,  4,  5])

In [46]:
z.sort()
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# 2 dimensinal Array

In [47]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
b = np.array([[7,8,9], [10,11,12]])
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [49]:
np.concatenate((a,b), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [50]:
np.concatenate((a,b),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [51]:
h = np.array([[[10,11],[12,13]],
              [[14,15],[16,17]],
              [[18,19],[20,21]]])
h

array([[[10, 11],
        [12, 13]],

       [[14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21]]])

In [52]:
h.ndim

3

In [53]:
h.size

12

In [71]:
h = np.arange(9)
h

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [72]:
i = h.reshape(3,3)
i

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [73]:
np.reshape(i, newshape=(1,9), order='C')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [74]:
j = h[np.newaxis, :]  # row wise
j

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [76]:
j.shape

(1, 9)

In [77]:
k = h[: ,np.newaxis]   # coloumn wise
k

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])